name: CI

on: [push]  # Runs when you push changes

jobs:
  build:
    runs-on: ubuntu-latest  # Uses a virtual machine
    steps:
    - uses: actions/checkout@v2  # Gets your code
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Uses Python 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pip install pytest  # Installs the testing tool
        pytest tests/  # Runs your tests